package org.qiuyeqaq.gtl_extend.common.multiblock.structure.Void_Pump;

public class Void_Pump_Part1 {

    public static final String[] LAYER_001 = {
            "       B       ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
    };

    public static final String[] LAYER_002 = {
            "       B       ",
            "       B       ",
            "       B       ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
    };

    public static final String[] LAYER_003 = {
            "       B       ",
            "               ",
            "       B       ",
            "       B       ",
            "       B       ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "       B       ",
            "       B       ",
            "       B       ",
            "       B       ",
            "       B       ",
            "       B       ",
            "       B       ",
            "               ",
            "               ",
    };

    public static final String[] LAYER_004 = {
            "               ",
            "       B       ",
            "       B       ",
            "       B       ",
            "    BBBBBBB    ",
            "       B       ",
            "       B       ",
            "       B       ",
            "       B       ",
            "       B       ",
            "       B       ",
            "    B  B  B    ",
            "       B       ",
            "       B       ",
            "   BB  B  B    ",
            "   B CCCCC B   ",
            "   B CCCCC B   ",
            "   B CCCCC B   ",
            "   B CCCCC B   ",
            "   B CCCCC B   ",
            "   B BBBBB B   ",
            "               ",
            "               ",
    };

    public static final String[] LAYER_005 = {
            "    CC   CC    ",
            "    C     C    ",
            "    C     C    ",
            "    C     C    ",
            "   BC     CB   ",
            "    C     C    ",
            "    C  E  C    ",
            "    C     C    ",
            "    C     C    ",
            "    C     C    ",
            "    CCCCCCC    ",
            "   BCBBBBBCB   ",
            "    C     C    ",
            "    C     C    ",
            "   BCBBBBBCB   ",
            "    CCCCCCC    ",
            "    C     C    ",
            "    C     C    ",
            "    C     C    ",
            "    CCCCCCC    ",
            "    BCCCCCB    ",
            "    B     B    ",
            "    CCCCCCC    ",
    };

    public static final String[] LAYER_006 = {
            "    C     C    ",
            "               ",
            "               ",
            "               ",
            "   B   E   B   ",
            "      EEE      ",
            "      EEE      ",
            "       E       ",
            "               ",
            "               ",
            "    C     C    ",
            "    B  B  B    ",
            "       B       ",
            "     CCCCC     ",
            "    BCCCCCB    ",
            "   CCCCCCCCC   ",
            "   C       C   ",
            "   C       C   ",
            "   C       C   ",
            "   CCC   CCC   ",
            "   BCCCCCCCB   ",
            "     CCCCC     ",
            "    CCCACCC    ",
    };

    public static final String[] LAYER_007 = {
            "               ",
            "               ",
            "               ",
            "       E       ",
            "   B  EEE  B   ",
            "     EEEEE     ",
            "     EEEEE     ",
            "      EEE      ",
            "      EEE      ",
            "       E       ",
            "    C BEB C    ",
            "    B CCC B    ",
            "      CCC      ",
            "     CCCCC     ",
            "    BC   CB    ",
            "   CCC   CCC   ",
            "   C       C   ",
            "   C       C   ",
            "   C       C   ",
            "   CC     CC   ",
            "   BCCCCCCCB   ",
            "     CCCCC     ",
            "    CCAAACC    ",
    };

    public static final String[] LAYER_008 = {
            "BBB         BBB",
            " B B       B B ",
            " BBB   D   BBB ",
            "  BB  EEE  BB  ",
            "  BB EEEEE BB  ",
            "   B EEEEE B   ",
            "   BEEEEEEEB   ",
            "   B EEEEE B   ",
            "   B  EEE  B   ",
            "   B  EEE  B   ",
            "   BC EEE CB   ",
            "   BBBCCCBBB   ",
            "   B BC CB B   ",
            "   B CC CC B   ",
            "  BBBC   CBBB  ",
            "  BCCC   CCCB  ",
            "  BC       CB  ",
            "  BC       CB  ",
            "  BC       CB  ",
            "  BCC     CCB  ",
            "  BBCCCCCCCBB  ",
            "     CCCCC     ",
            "    CAA~AAC    ",
    };

    public static final String[] LAYER_009 = {
            "               ",
            "               ",
            "               ",
            "       E       ",
            "   B  EEE  B   ",
            "     EEEEE     ",
            "     EEEEE     ",
            "      EEE      ",
            "      EEE      ",
            "       E       ",
            "    C BEB C    ",
            "    B CCC B    ",
            "      CCC      ",
            "     CCCCC     ",
            "    BC   CB    ",
            "   CCC   CCC   ",
            "   C       C   ",
            "   C       C   ",
            "   C       C   ",
            "   CC     CC   ",
            "   BCCCCC CB   ",
            "     CCCCC     ",
            "    CCAAACC    ",
    };

    public static final String[] LAYER_010 = {
            "    C     C    ",
            "               ",
            "               ",
            "               ",
            "   B   E   B   ",
            "      EEE      ",
            "     EEEE      ",
            "       E       ",
            "               ",
            "               ",
            "    C     C    ",
            "    B  B  B    ",
            "       B       ",
            "     CCCCC     ",
            "    BCCCCCB    ",
            "   CCCCCCCCC   ",
            "   C       C   ",
            "   C       C   ",
            "   C       C   ",
            "   CCC   CCC   ",
            "   BCCCCCCCB   ",
            "     CCCCC     ",
            "    CCCACCC    ",
    };

    public static final String[] LAYER_011 = {
            "    CC   CC    ",
            "    C     C    ",
            "    C     C    ",
            "    C     C    ",
            "   BC     CB   ",
            "    C     C    ",
            "    C  E  C    ",
            "    C     C    ",
            "    C     C    ",
            "    C     C    ",
            "    CCCCCCC    ",
            "   BCBBBBBCB   ",
            "    C     C    ",
            "    C     C    ",
            "   BCBBBBBCB   ",
            "    CCCCCCC    ",
            "    C     C    ",
            "    C     C    ",
            "    C     C    ",
            "    CCCCCCC    ",
            "    BCCCCCB    ",
            "    B     B    ",
            "    CCCCCCC    ",
    };

    public static final String[] LAYER_012 = {
            "               ",
            "       B       ",
            "       B       ",
            "       B       ",
            "    BBBBBBB    ",
            "       B       ",
            "       B       ",
            "       B       ",
            "       B       ",
            "       B       ",
            "       B       ",
            "    B  B  B    ",
            "       B       ",
            "       B       ",
            "    B  B  B    ",
            "   B CCCCC B   ",
            "   B CCCCC B   ",
            "   B CCCCC B   ",
            "   B CCCCC B   ",
            "   B CCCCC B   ",
            "   B BBBBB B   ",
            "               ",
            "               ",
    };

    public static final String[] LAYER_013 = {
            "       B       ",
            "               ",
            "       B       ",
            "       B       ",
            "       B       ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "       B       ",
            "       B       ",
            "       B       ",
            "       B       ",
            "       B       ",
            "       B       ",
            "       B       ",
            "               ",
            "               ",
    };

    public static final String[] LAYER_014 = {
            "       B       ",
            "       B       ",
            "       B       ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
    };

    public static final String[] LAYER_015 = {
            "       B       ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
            "               ",
    };
}
