modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors="qiuyeqaq, 荀彧，疏影"
description = "增加了一系列的超级机器(虽然很贵就是了),一些贴图由荀彧提供，一些结构由疏影提供"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "gtceu"
mandatory = true
versionRange = "[${gtceu_version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "ae2"
mandatory = true
versionRange = "[15.2.,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "ad_astra"
mandatory = true
versionRange = "[${ad_astra_version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "gtmthings"
mandatory = true
versionRange = "[1.3,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "kubejs"
mandatory = false
versionRange = "[${kubejs_version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "jei"
mandatory = false
versionRange = "[${jei_version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "extendedae"
mandatory = false
versionRange = "[1.1,)"
ordering = "AFTER"
side = "BOTH"